### ISSUE TITLE
Issue with Push to remote  and git branches

### ISSUE THREAD

**Issue by bardicreels** [breck7/ScrollHub#15]
When trying to push local to remote live server in production, it frequently causes HEAD and branch issues because the remote keeps updating logs with records of new visitors

i have added every log file in the production server to gitignore here:

https://github.com/bardicreels/ScrollHub/blob/5de7235bcddf2f7ada318023eb8647df8ab834d9/.gitignore

but there may be a more elegant solution i am not aware of.

**Comment by breck7** [comment]
Ah I've been hitting this to. Okay I'm on it. Will try and have long term fix in 1 - 3 hours. Gotta think this one through first.

**Comment by bardicreels** [comment]
the only issue with relying on the .gitignore list is that it's not scroll-like and dynamic, future development will break the reliance on the file

**Comment by breck7** [comment]
> the only issue with relying on the .gitignore list is that it's not scroll-like and dynamic, future development will break the reliance on the file

Yes scroll and .gitignore are not working seamlessly with each other.

I'm trying to visualize the most common flows now and imagine them in the future and figure out what the core concepts are and what we need to track and not track with git. There's gotta be a few simple rules that will make everything work as people need and expect.

**Comment by breck7** [comment]
Okay I've used the hidden file pattern where all autogenerated Scroll files begin with a ".", and then we just add ".*" to gitignores.

Seems to be working, but we can reopen if this doesnt solve it
