### ISSUE TITLE
changing directory breaks npm run update

### ISSUE THREAD

**Issue by bardicreels** [breck7/ScrollHub#21]
npm run update package.json is still looking for files using a previous directory structure

stdout:
'''
npm run update
npm error code ENOENT
npm error syscall open
npm error path /root/package.json
npm error errno -2
npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/root/package.json'
npm error enoent This is related to npm not being able to find a file.
npm error enoent
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-11-13T21_49_47_671Z-debug-0.log
'''

**Comment by breck7** [comment]
try `npm run update` in the ScrollHub folder.

npm will always look for a package.json in whatever folder it is currently in.

**Comment by breck7** [comment]
Will close for now but lemme know if that didnt fix it
